apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-backend
  labels:
    app: sms-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sms-backend
  template:
    metadata:
      labels:
        app: sms-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: sms-backend
        image: 371104899767.dkr.ecr.ap-south-1.amazonaws.com/sms-backend:latest 
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: sms-config
        - secretRef:
            name: sms-secret
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
