name: Deploy App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Build & Push
      run: |
        docker build -t yourusername/backend ./backend
        docker push yourusername/backend

    - name: Deploy to EC2
      run: |
        ssh ubuntu@your-ip "
        docker pull yourusername/backend &&
        docker stop backend || true &&
        docker rm backend || true &&
        docker run -d -p 5000:5000 --name backend yourusername/backend
        "